spring:
  security:
    oauth2:
      client:
        registration:
          google-dev:
            client-id: client-id
            client-secret: client-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            # redirect-uri: http://localhost:8080/login/oauth2/code/google-dev
            scope: openid,email,profile
            client-name: google-dev

        provider:
          google-dev:
            issuer-uri: https://accounts.google.com
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
